# db/seeds/users_companies_roles.rb

forwarder = Company.create!(
  japanese_name: "ABCフォワーダー株式会社",
  english_name: "ABC Forwarder Co., Ltd.",
  address: "Tokyo",
  is_forwarder: true
)

# Agent
agents = 5.times.map do |i|
  Company.create!(
    japanese_name: "代理店#{i+1}株式会社",
    english_name: "Agent #{i+1} Co., Ltd.",
    address: "CityA#{i}",
    is_forwarder: false
  )
end

# Shipper
shippers = 5.times.map do |i|
  Company.create!(
    japanese_name: "シッパー商事#{i+1}株式会社",
    english_name: "Shipper Trading #{i+1} Inc.",
    address: "CityB#{i}",
    is_forwarder: false
  )
end

# Consignee
consignees = 5.times.map do |i|
  Company.create!(
    japanese_name: "コンサイニー物流#{i+1}株式会社",
    english_name: "Consignee Logistics #{i+1} Ltd.",
    address: "CityC#{i}",
    is_forwarder: false
  )
end

# Custom (通関業者)
customs = 5.times.map do |i|
  Company.create!(
    japanese_name: "税関通関#{i+1}株式会社",
    english_name: "Customs Broker #{i+1} Co., Ltd.",
    address: "CityD#{i}",
    is_forwarder: false
  )
end

# 複数役割兼務の会社例
agent_and_consignee = Company.create!(
  japanese_name: "エーシー商事株式会社",
  english_name: "AC Corporation",
  address: "CityE1",
  is_forwarder: false
)

shipper_and_custom = Company.create!(
  japanese_name: "エスシー物流株式会社",
  english_name: "SC Logistics Ltd.",
  address: "CityE2",
  is_forwarder: false
)

0.upto(5) do |num|
  BusinessCategory.create!(category: num)
end

CompanyBusinessCategory.create!(company_id: agent_and_consignee.id, business_category_id: BusinessCategory.find_by(category: :agent).id)
CompanyBusinessCategory.create!(company_id: agent_and_consignee.id, business_category_id: BusinessCategory.find_by(category: :consignee).id)
CompanyBusinessCategory.create!(company_id: shipper_and_custom.id, business_category_id: BusinessCategory.find_by(category: :shipper).id)
CompanyBusinessCategory.create!(company_id: shipper_and_custom.id, business_category_id: BusinessCategory.find_by(category: :custom).id)

# --- Users ---
users = []

# Forwarder Users
users << User.create!(
  email: "forwarder_admin@example.com",
  password: "password",
  company: forwarder,
  role: 0,
  name: "Forwarder Admin"
)
users << User.create!(
  email: "forwarder_editor@example.com",
  password: "password",
  company: forwarder,
  role: 0,
  name: "Forwarder Editor"
)
users << User.create!(
  email: "forwarder_viewer@example.com",
  password: "password",
  company: forwarder,
  role: 0,
  name: "Forwarder Viewer"
)

# 他会社 Users
[agents, shippers, consignees, customs].each_with_index do |company_list, i|
  email = case i
  when 0
    "agent"
  when 1
    "shipper"
  when 2
    "consignee"
  when 3
    "custom"
  end
  company_list.each_with_index do |c, si|
    users << User.create!(
      email: "#{email}#{si}_editor@example.com",
      password: "password",
      company: c,
      role: 1,
      name: "#{email}#{si} Editor"
    )
    users << User.create!(
      email: "#{email}#{si}_viewer@example.com",
      password: "password",
      company: c,
      role: 1,
      name: "#{email}#{si} Viewer"
    )
  end
end

# 兼務会社 Users
[agent_and_consignee, shipper_and_custom].each_with_index do |c, i|
  email = i.zero? ? "agent_and_consignee" : "shipper_and_custom"
  users << User.create!(
    email: "#{email}_editor@example.com",
    password: "password",
    company: c,
    role: 2,
    name: "#{email}#{i} Editor"
  )
  users << User.create!(
    email: "#{email}_viewer@example.com",
    password: "password",
    company: c,
    role: 2,
    name: "#{email}#{i} Viewer"
  )
end

User.update_all confirmed_at: DateTime.now
puts "Seeded #{Company.count} companies, #{User.count} users"

ports = [
  # // 確認済み（調査で確認できたもの）
  {name: "ADEN", port_code: "YEADE"},
  {name: "HAMBURG", port_code: "DEHAM"},
  {name: "TOKYO", port_code: "JPTYO"},
  {name: "YOKOHAMA", port_code: "JPYOK"},
  {name: "SHANGHAI", port_code: "CNSHA"},
  {name: "ROTTERDAM", port_code: "NLRTM"},
  {name: "SINGAPORE", port_code: "SGSIN"},
  {name: "HONG KONG", port_code: "HKHKG"},
  {name: "ANTWERP", port_code: "BEANR"},
  {name: "SHENZHEN", port_code: "CNSZX"},
  {name: "NINGBO", port_code: "CNNGB"},
  {name: "QINGDAO", port_code: "CNTAO"},
  {name: "GUANGZHOU", port_code: "CNCAN"},
  {name: "TIANJIN", port_code: "CNTSN"},
  {name: "PUSAN", port_code: "KRPUS"},
  # // ヨーロッパ
  {name: "AARHUS", port_code: "DKAAR"},
  {name: "ABERDEEN", port_code: "GBABD"},
  {name: "AMSTERDAM", port_code: "NLAMS"},
  {name: "ANCONA", port_code: "ITAON"},
  {name: "BARCELONA", port_code: "ESBCN"},
  {name: "BARI", port_code: "ITBRI"},
  {name: "BASEL", port_code: "CHBSL"},
  {name: "BELFAST", port_code: "GBBFS"},
  {name: "BERGEN", port_code: "NOBGN"},
  {name: "BILBAO", port_code: "ESBIO"},
  {name: "BOLOGNA", port_code: "ITBLQ"},
  {name: "BREMEN", port_code: "DEBRV"},
  {name: "BREMERHAVEN", port_code: "DEBRV"},
  {name: "BRUSSELS", port_code: "BEBRU"},
  {name: "COPENHAGEN", port_code: "DKCPH"},
  {name: "CORK", port_code: "IECRK"},
  {name: "DUBLIN", port_code: "IEDUB"},
  {name: "ESBJERG", port_code: "DKESB"},
  {name: "FLORENCE", port_code: "ITFLR"},
  {name: "GDANSK", port_code: "PLGDN"},
  {name: "GDYNIA", port_code: "PLGDY"},
  {name: "GENEVA", port_code: "CHGVA"},
  {name: "GENOVA", port_code: "ITGOA"},
  {name: "GLASGOW", port_code: "GBGLW"},
  {name: "GOTHENBURG", port_code: "SEGOT"},
  {name: "GRANGEMOUTH", port_code: "GBGRG"},
  {name: "HELSINGBORG", port_code: "SEHBG"},
  {name: "HELSINKI", port_code: "FIHEL"},
  {name: "KATOWICE", port_code: "PLKTW"},
  {name: "KOTKA", port_code: "FIKTK"},
  {name: "KRAKOW", port_code: "PLKRK"},
  {name: "LA SPEZIA", port_code: "ITLSP"},
  {name: "LE HAVRE", port_code: "FRLEH"},
  {name: "LEIXOES", port_code: "PTLEX"},
  {name: "LIVORNO", port_code: "ITLIV"},
  {name: "LODZ", port_code: "PLLCJ"},
  {name: "LONDON", port_code: "GBLON"},
  {name: "LYON", port_code: "FRLYS"},
  {name: "MALAGA", port_code: "ESAGP"},
  {name: "MALMO", port_code: "SEMMA"},
  {name: "MARSEILLES", port_code: "FRMRS"},
  {name: "MESSINA", port_code: "ITMSN"},
  {name: "MILAN", port_code: "ITMIL"},
  {name: "MODENA", port_code: "ITMOD"},
  {name: "MUNICH", port_code: "DEMUC"},
  {name: "NAPLES", port_code: "ITNAP"},
  {name: "OSLO", port_code: "NOOSL"},
  {name: "PALERMO", port_code: "ITPMO"},
  {name: "PALMA DE MALLORCA", port_code: "ESPMI"},
  {name: "PARIS G", port_code: "FRPAR"},
  {name: "PASAJES", port_code: "ESPAS"},
  {name: "PIRAEUS", port_code: "GRPIR"},
  {name: "PISA", port_code: "ITPSA"},
  {name: "PLYMOUTH", port_code: "GBPLY"},
  {name: "POZNAN", port_code: "PLPOZ"},
  {name: "PRAGUE", port_code: "CZPRG"},
  {name: "RAVENNA", port_code: "ITRAV"},
  {name: "RIGA", port_code: "LVRIX"},
  {name: "RIJEKA", port_code: "HRRJK"},
  {name: "ROME", port_code: "ITROM"},
  {name: "ROSTOCK", port_code: "DERST"},
  {name: "SAINT PETERSBURG", port_code: "RULED"},
  {name: "SALERNO", port_code: "ITSAL"},
  {name: "STOCKHOLM", port_code: "SESTO"},
  {name: "STUTTGART", port_code: "DESTR"},
  {name: "TALLINN", port_code: "EETLL"},
  {name: "TARANTO", port_code: "ITTAR"},
  {name: "THESSALONIKI", port_code: "GRTHE"},
  {name: "TRIESTE", port_code: "ITTRS"},
  {name: "TURIN", port_code: "ITTRN"},
  {name: "TURKU", port_code: "FITUR"},
  {name: "VALENCIA", port_code: "ESVLC"},
  {name: "VALLETTA", port_code: "MTVLA"},
  {name: "VARNA", port_code: "BGVAR"},
  {name: "VENICE", port_code: "ITVCE"},
  {name: "VERONA", port_code: "ITVNA"},
  {name: "VIGO", port_code: "ESVGO"},
  {name: "VLORE", port_code: "ALVLR"},
  {name: "VOLOS", port_code: "GRVOL"},
  {name: "WARSAW", port_code: "PLWAW"},
  {name: "ZURICH", port_code: "CHZUR"},

  # // アジア
  {name: "BANGKOK", port_code: "THBKK"},
  {name: "CHENNAI", port_code: "INMAA"},
  {name: "CHIBA", port_code: "JPCHB"},
  {name: "CHITTAGONG", port_code: "BDCGP"},
  {name: "CHONGJIN", port_code: "KPCHJ"},
  {name: "COCHIN", port_code: "INCOK"},
  {name: "COLOMBO", port_code: "LKCMB"},
  {name: "DAILIAN", port_code: "CNDLC"},
  {name: "DONG GUAN", port_code: "CNDGG"},
  {name: "FUZHOU", port_code: "CNFOC"},
  {name: "HACHINOHE", port_code: "JPHNJ"},
  {name: "HAIKOU", port_code: "CNHAK"},
  {name: "HAKATA", port_code: "JPHKT"},
  {name: "HALDIA", port_code: "INHLD"},
  {name: "HANGZHOU", port_code: "CNHGH"},
  {name: "HIROSHIMA", port_code: "JPHIJ"},
  {name: "HITACHI", port_code: "JPHTI"},
  {name: "HUANGPU", port_code: "CNHUP"},
  {name: "IMABARI", port_code: "JPIMB"},
  {name: "INCHEON", port_code: "KRICN"},
  {name: "JAKARTA", port_code: "IDJKT"},
  {name: "JAMBI", port_code: "IDJMB"},
  {name: "JAWAHARLAL NEHRU", port_code: "INJNP"},
  {name: "JIANGMEN", port_code: "CNJGM"},
  {name: "JOHARBAHRU", port_code: "MYJHB"},
  {name: "KAGOSHIMA", port_code: "JPKOJ"},
  {name: "KANDLA", port_code: "INKDL"},
  {name: "KAOHSIUNG", port_code: "TWKHH"},
  {name: "KEELUNG", port_code: "TWKEL"},
  {name: "KOBE", port_code: "JPUKB"},
  {name: "KOLKATA", port_code: "INCCU"},
  {name: "KOTA KINABALU", port_code: "MYKKI"},
  {name: "KUALA BELAIT", port_code: "BNKBT"},
  {name: "KUANTAN", port_code: "MYKUA"},
  {name: "KUCHING", port_code: "MYKCH"},
  {name: "LAEM CHABANG", port_code: "THLCB"},
  {name: "LAHAD DATU", port_code: "MYLHD"},
  {name: "LIANYUNGANG", port_code: "CNLYG"},
  {name: "MACAU", port_code: "MOMFM"},
  {name: "MANILA", port_code: "PHMNL"},
  {name: "MEDAN", port_code: "IDMDN"},
  {name: "MIZUSHIMA", port_code: "JPMZM"},
  {name: "MOJI", port_code: "JPMJI"},
  {name: "MUMBAI", port_code: "INBOM"},
  {name: "MUNDRA", port_code: "INMDR"},
  {name: "NAGOYA", port_code: "JPNGO"},
  {name: "NAHA", port_code: "JPNHA"},
  {name: "NAKHODKA", port_code: "RUNHK"},
  {name: "NAMPO", port_code: "KPNMP"},
  {name: "NANJING", port_code: "CNNJG"},
  {name: "NEW MANGALORE", port_code: "INMNG"},
  {name: "NIIGATA", port_code: "JPKIJ"},
  {name: "OSAKA", port_code: "JPOSA"},
  {name: "PADANG", port_code: "IDPDG"},
  {name: "PALEMBANG", port_code: "IDPLM"},
  {name: "PANJANG", port_code: "IDPJG"},
  {name: "PARADEEP", port_code: "INPRD"},
  {name: "PENANG", port_code: "MYPKG"},
  {name: "PHNOM PENH", port_code: "KHPNH"},
  {name: "PIPAVAV", port_code: "INPPV"},
  {name: "PORT KELANG", port_code: "MYPKG"},
  {name: "QUANZHOU", port_code: "CNQZH"},
  {name: "SAKAI", port_code: "JPSKA"},
  {name: "SAKAIMINATO", port_code: "JPSKM"},
  {name: "SANDAKAN", port_code: "MYSDK"},
  {name: "SEMARANG", port_code: "IDSMG"},
  {name: "SENBOKU", port_code: "JPSNB"},
  {name: "SENDAI", port_code: "JPSND"},
  {name: "SHANTOU", port_code: "CNSWX"},
  {name: "SHAOXING", port_code: "CNSHX"},
  {name: "SHEKOU", port_code: "CNSHK"},
  {name: "SHIBUSHI", port_code: "JPSHB"},
  {name: "SHIMIZU", port_code: "JPSHZ"},
  {name: "SHIQI", port_code: "CNSHQ"},
  {name: "SIBU", port_code: "MYSBU"},
  {name: "SIHANOUKVILLE", port_code: "KHKOS"},
  {name: "SONGKHLA", port_code: "THSGZ"},
  {name: "SURABAYA", port_code: "IDSUB"},
  {name: "SUZHOU", port_code: "CNSZH"},
  {name: "TAICHUNG", port_code: "TWTXG"},
  {name: "TAIPEI", port_code: "TWTPE"},
  {name: "TAWAU", port_code: "MYTWU"},
  {name: "TOMAKOMAI", port_code: "JPTMK"},
  {name: "TOYAMA", port_code: "JPTOY"},
  {name: "TUTICORIN", port_code: "INTUT"},
  {name: "VISAKHAPATNAM", port_code: "INVTZ"},
  {name: "VLADIVOSTOK", port_code: "RUVVO"},
  {name: "WEIHAI", port_code: "CNWEH"},
  {name: "WENZHOU", port_code: "CNWZH"},
  {name: "WU HAN", port_code: "CNWUH"},
  {name: "WUHU", port_code: "CNWHU"},
  {name: "WUXI", port_code: "CNWXI"},
  {name: "WUZHOU", port_code: "CNWUZ"},
  {name: "XIAMEN", port_code: "CNXMN"},
  {name: "YANGON", port_code: "MMRGN"},
  {name: "YANGZHOU", port_code: "CNYZH"},
  {name: "YANTAI", port_code: "CNYNT"},
  {name: "YOKKAICHI", port_code: "JPYKK"},
  {name: "ZHANGJIAGANG", port_code: "CNZJG"},
  {name: "ZHANJIANG", port_code: "CNZHA"},
  {name: "ZHAOQING", port_code: "CNZHQ"},
  {name: "ZHUHAI", port_code: "CNZUH"},

  # // 中東・アフリカ
  {name: "ABIDJAN", port_code: "CIABJ"},
  {name: "ADABIYA", port_code: "EGADA"},
  {name: "AGADIR", port_code: "MAAGA"},
  {name: "AL JUBAIL", port_code: "SAJUB"},
  {name: "ALEXANDRIA", port_code: "EGALY"},
  {name: "ALGIERS", port_code: "DZALG"},
  {name: "ANNABA", port_code: "DZAAE"},
  {name: "APAPA", port_code: "NGAPA"},
  {name: "AQABA", port_code: "JOAQJ"},
  {name: "ASHDOD", port_code: "ILASD"},
  {name: "ASSAB", port_code: "ERASSB"},
  {name: "BANDAR ABBAS", port_code: "IRBND"},
  {name: "BANDAR KHOMEINI", port_code: "IRBKH"},
  {name: "BANJUL", port_code: "GMBJL"},
  {name: "BEIRA", port_code: "MZBEI"},
  {name: "BEIRUT", port_code: "LBBEY"},
  {name: "BENGHAZI", port_code: "LYBNJ"},
  {name: "BERBERA", port_code: "SOBER"},
  {name: "BIZERTE", port_code: "TNBIZ"},
  {name: "CAPE TOWN", port_code: "ZACPT"},
  {name: "CASABLANCA", port_code: "MACAS"},
  {name: "COTONOU", port_code: "BJCOO"},
  {name: "DAKAR", port_code: "SNDKR"},
  {name: "DAMIETTA", port_code: "EGDAM"},
  {name: "DAMMAM", port_code: "SADAM"},
  {name: "DAR ES SALAAM", port_code: "TZDAR"},
  {name: "DIEGO SUAREZ", port_code: "MGANT"},
  {name: "DJIBOUTI", port_code: "DJJIB"},
  {name: "DOHA", port_code: "QADOH"},
  {name: "DOUALA", port_code: "CMDLA"},
  {name: "DURBAN", port_code: "ZADUR"},
  {name: "EAST LONDON", port_code: "ZAELS"},
  {name: "FREETOWN", port_code: "SLFNA"},
  {name: "GABES", port_code: "TNGAB"},
  {name: "HAIFA", port_code: "ILHFA"},
  {name: "HODEIDAH", port_code: "YEHOD"},
  {name: "ISKENDERUN", port_code: "TRISK"},
  {name: "ISTANBUL", port_code: "TRIST"},
  {name: "IZMIR", port_code: "TRADB"},
  {name: "JEDDAH", port_code: "SAJED"},
  {name: "KISH ISLAND", port_code: "IRKSH"},
  {name: "KISMAYA", port_code: "SOKIS"},
  {name: "LAGOS", port_code: "NGLOS"},
  {name: "LARNACA", port_code: "CYLCA"},
  {name: "LAS PALMAS", port_code: "ESLPA"},
  {name: "LATTAKIA", port_code: "SYLAT"},
  {name: "LIBREVILLE", port_code: "GALIB"},
  {name: "LIMASSOL", port_code: "CYLMS"},
  {name: "LOBITO", port_code: "AOLOB"},
  {name: "LOME", port_code: "TGLFW"},
  {name: "LUANDA", port_code: "AOLAD"},
  {name: "LUDERITZ", port_code: "NALUD"},
  {name: "MAHE", port_code: "SCMAH"},
  {name: "MAJUNGA", port_code: "MGMJN"},
  {name: "MANAMA", port_code: "BHBAH"},
  {name: "MAPUTO", port_code: "MZMPM"},
  {name: "MASSAWA", port_code: "ERMSA"},
  {name: "MERSIN", port_code: "TRICE"},
  {name: "MISRATAH", port_code: "LYMRA"},
  {name: "MOGADISHU", port_code: "SOMGQ"},
  {name: "MOMBASA", port_code: "KEMBA"},
  {name: "MORONI", port_code: "KMYVA"},
  {name: "MUSCAT", port_code: "OMMCT"},
  {name: "MUTSAMUDU", port_code: "KMMUT"},
  {name: "NACALA", port_code: "MZNCA"},
  {name: "NOUADHIBOU", port_code: "MRNDB"},
  {name: "NOUAKCHOTT", port_code: "MRNKC"},
  {name: "ORAN", port_code: "DZORN"},
  {name: "PORT ELIZABETH", port_code: "ZAPLZ"},
  {name: "PORT GENTIL", port_code: "GAPOG"},
  {name: "PORT HARCOURT", port_code: "NGPHC"},
  {name: "PORT LOUIS", port_code: "MUPLU"},
  {name: "PORT SUDAN", port_code: "SDPZU"},
  {name: "PORT SUEZ", port_code: "EGSUZ"},
  {name: "RADES", port_code: "TNRAD"},
  {name: "RICHARDS BAY", port_code: "ZARCB"},
  {name: "SALALAH", port_code: "OMSLL"},
  {name: "SFAX", port_code: "TNSFX"},
  {name: "SKIKDA", port_code: "DZSKI"},
  {name: "TAKORADI", port_code: "GHTKD"},
  {name: "TAMATAVE", port_code: "MGTMT"},
  {name: "TANGA", port_code: "TZTGA"},
  {name: "TEMA", port_code: "GHTEM"},
  {name: "TINCAN ISLAND", port_code: "NGTIN"},
  {name: "TRABZON", port_code: "TRTBZ"},
  {name: "TRIPOLI", port_code: "LYTIP"},
  {name: "UMM QASR", port_code: "IQUMQ"},
  {name: "UMM SAID", port_code: "QAUMD"},
  {name: "WALVIS BAY", port_code: "NAWVB"},
  {name: "ZANZIBAR", port_code: "TZZNZ"},

  # // 南北アメリカ
  {name: "ACAPULCO", port_code: "MXACA"},
  {name: "ALTAMIRA", port_code: "MXATM"},
  {name: "BAHIA", port_code: "BRSSA"},
  {name: "BALBOA", port_code: "PABAL"},
  {name: "BARRANQUILLA", port_code: "COBAQ"},
  {name: "BELEM", port_code: "BRBEL"},
  {name: "BELIZE", port_code: "BZBZE"},
  {name: "BRIDGETOWN", port_code: "BBBGI"},
  {name: "BUENAVENTURA", port_code: "COBUN"},
  {name: "BUENOS AIRES", port_code: "ARBUE"},
  {name: "CALLAO", port_code: "PECLL"},
  {name: "CARTAGENA", port_code: "COCTG"},
  {name: "COLON", port_code: "PACLN"},
  {name: "CORINTO", port_code: "NICIN"},
  {name: "CRISTOBAL", port_code: "PACRB"},
  {name: "CURACAO", port_code: "CWCUR"},
  {name: "ENSENADA", port_code: "MXENS"},
  {name: "FORTALEZA", port_code: "BRFOR"},
  {name: "GUAYAQUIL", port_code: "ECGYE"},
  {name: "HALIFAX", port_code: "CAHAL"},
  {name: "HAVANA", port_code: "CUHAV"},
  {name: "KINGSTON", port_code: "JMKIN"},
  {name: "KINGSTOWN", port_code: "VCSVU"},
  {name: "LAZARO CARDENAS", port_code: "MXLZC"},
  {name: "MANTA", port_code: "ECMNT"},
  {name: "MANZANILLO", port_code: "MXMAN"},
  {name: "MATANZAS", port_code: "CUMTQ"},
  {name: "MEXICO CITY", port_code: "MXMEX"},
  {name: "MONTREAL", port_code: "CAMTR"},
  {name: "NASSAU", port_code: "BSNAS"},
  {name: "PANAMA CITY", port_code: "PAPAC"},
  {name: "PARANAGUA", port_code: "BRPNG"},
  {name: "PORT-AU-PRINCE", port_code: "HTPAP"},
  {name: "PORTOALEGRE", port_code: "BRPOA"},
  {name: "PRINCE RUPERT", port_code: "CAPRZ"},
  {name: "PUERTO CALDERA", port_code: "CRPCR"},
  {name: "PUERTO CORTES", port_code: "HNPCO"},
  {name: "PUERTO LIMON", port_code: "CRPLM"},
  {name: "PUERTO QUETZAL", port_code: "GTPQU"},
  {name: "PUNTA ARENAS", port_code: "CLPUN"},
  {name: "PUNTARENAS", port_code: "CRPNT"},
  {name: "RECIFE", port_code: "BRREC"},
  {name: "RIO DE JANEIRO", port_code: "BRRIO"},
  {name: "RIO GRANDE", port_code: "BRRIG"},
  {name: "ROSARIO", port_code: "ARROS"},
  {name: "ROSEAU", port_code: "DMROO"},
  {name: "SALVADOR", port_code: "BRSAL"},
  {name: "SAN ANTONIO", port_code: "CLSAI"},
  {name: "SAN JUAN", port_code: "PRSJU"},
  {name: "SANTA MARTA", port_code: "COSMR"},
  {name: "SANTIAGO", port_code: "CLSCL"},
  {name: "SANTO DOMINGO", port_code: "DOSDQ"},
  {name: "SANTOS", port_code: "BRSSZ"},
  {name: "SAO FRANCISCO DO SUL", port_code: "BRSFS"},
  {name: "TAMPICO", port_code: "MXTAM"},
  {name: "TORONTO", port_code: "CATOR"},
  {name: "USHUAIA", port_code: "ARUSH"},
  {name: "VALDEZ", port_code: "USVDZ"},
  {name: "VALPARAISO", port_code: "CLVAP"},
  {name: "VANCOUVER", port_code: "CAVAN"},
  {name: "VERA CRUZ", port_code: "MXVER"},
  {name: "VITORIA", port_code: "BRVIX"},

  # // オセアニア・太平洋
  {name: "ALOTAU", port_code: "PGALP"},
  {name: "AUCKLAND", port_code: "NZAKL"},
  {name: "BLUFF", port_code: "NZBLF"},
  {name: "CHRISTCHURCH", port_code: "NZCHC"},
  {name: "DUNEDIN", port_code: "NZDUD"},
  {name: "EBEYE", port_code: "MHEBY"},
  {name: "FUNAFUTI", port_code: "TVFUN"},
  {name: "HONIARA", port_code: "SBHIR"},
  {name: "HONOLULU", port_code: "USHNL"},
  {name: "INVERCARGILL", port_code: "NZIVC"},
  {name: "KAVIENG", port_code: "PGKVG"},
  {name: "KIMBE", port_code: "PGKMB"},
  {name: "KOROR", port_code: "PWROR"},
  {name: "LAE", port_code: "PGLAE"},
  {name: "LAUTTOKA", port_code: "FJLTK"},
  {name: "LYTTELTON", port_code: "NZLYT"},
  {name: "MADANG", port_code: "PGMAG"},
  {name: "MAJURO", port_code: "MHMAJ"},
  {name: "NAPIER", port_code: "NZNPE"},
  {name: "NELSON", port_code: "NZNSN"},
  {name: "NEW PLYMOUTH", port_code: "NZNPL"},
  {name: "NORO", port_code: "SBNRO"},
  {name: "NOUMEA", port_code: "NCNOU"},
  {name: "NUKUALOFA", port_code: "TONKU"},
  {name: "ORO BAY", port_code: "PGORB"},
  {name: "PAGO PAGO", port_code: "ASPPG"},
  {name: "PAPEETE", port_code: "PFPPT"},
  {name: "POHNPEI", port_code: "FMPNI"},
  {name: "PORT MORESBY", port_code: "PGPOM"},
  {name: "SAIPAN", port_code: "MPSPN"},
  {name: "SUVA", port_code: "FJSUV"},
  {name: "TAURANGA", port_code: "NZTBH"},
  {name: "TIMARU", port_code: "NZTIU"},
  {name: "VAVAU", port_code: "TOVAV"},
  {name: "WELLINGTON", port_code: "NZWLG"},
  {name: "WEWAK", port_code: "PGWWK"},

  # // その他（確認できなかった港は推定）
  {name: "APRILIA", port_code: "ITAPR"},
  {name: "BASSE-TERRE", port_code: "GPBAS"},
  {name: "BATU AMPAR", port_code: "IDBTM"},
  {name: "BEHIA", port_code: "BRBEH"},
  {name: "BELAWAN", port_code: "IDBLW"},
  {name: "BELHAI", port_code: "CNBLH"},
  {name: "BENGKULU", port_code: "IDBKL"},
  {name: "BERJAIA", port_code: "DZBJY"},
  {name: "BLANKA", port_code: "HRBLK"},
  {name: "BULAWAYO", port_code: "ZWBUW"},
  {name: "BURGAS", port_code: "BGBOJ"},
  {name: "BYDGOSZCZ", port_code: "PLBZG"},
  {name: "BYTOM", port_code: "PLBOM"},
  {name: "CALBAYOG", port_code: "PHCYP"},
  {name: "CAMBRIDGE", port_code: "GBCMG"},
  {name: "CARDOVA", port_code: "PHCRD"},
  {name: "CASSIBILE", port_code: "ITCAS"},
  {name: "CATANIA", port_code: "ITCTA"},
  {name: "CEBU", port_code: "PHCEB"},
  {name: "CEUTA", port_code: "EACEU"},
  {name: "CHANARAL", port_code: "CLCNR"},
  {name: "CIREBON", port_code: "IDCRB"},
  {name: "CONSTANZA", port_code: "ROCND"},
  {name: "CORDOBA", port_code: "ARCOR"},
  {name: "DAVAO", port_code: "PHDVO"},
  {name: "DEGIO SUAREZ", port_code: "MGDGS"},
  {name: "DERINCE", port_code: "TRDER"},
  {name: "DILI", port_code: "TLDLI"},
  {name: "DUMAN", port_code: "CNDMN"},
  {name: "DUO", port_code: "CNDUO"},
  {name: "DURRES", port_code: "ALDUR"},
  {name: "ENNORE", port_code: "INENO"},
  {name: "ESMERALDAS", port_code: "ECESM"},
  {name: "FAMAGUSTA", port_code: "CYFMG"},
  {name: "FANCHENG", port_code: "CNFCG"},
  {name: "FLUSHING", port_code: "NLVLI"},
  {name: "FOS", port_code: "FRFOS"},
  {name: "FOSHAN", port_code: "CNFOS"},
  {name: "GATUN", port_code: "PAGTL"},
  {name: "GENERAL SANTOS", port_code: "PHGSC"},
  {name: "GRANADA", port_code: "ESGRD"},
  {name: "GUADALAJARA", port_code: "MXGDL"},
  {name: "HARARE", port_code: "ZWHRE"},
  {name: "HSINGKANG", port_code: "CNHSK"},
  {name: "IQUIQUE", port_code: "CLIQQ"},
  {name: "ITAJAI", port_code: "BRITJ"},
  {name: "IWAKI", port_code: "JPIWK"},
  {name: "JOHANNESBURG", port_code: "ZAJNB"},
  {name: "KABIL", port_code: "AFKBL"},
  {name: "KAMPONGSOM", port_code: "KHKOS"},
  {name: "KAVALLA", port_code: "GRKAV"},
  {name: "KUPANG", port_code: "IDKPG"},
  {name: "KUWAIT L", port_code: "KWKWI"},
  {name: "LABUAN", port_code: "MYLBN"},
  {name: "LACENA", port_code: "ITLAC"},
  {name: "LATINA", port_code: "ITLAT"},
  {name: "LIRQUEN", port_code: "CLLQN"},
  {name: "LLOILO", port_code: "PHILO"},
  {name: "LUDA", port_code: "CNLUD"},
  {name: "LUDWIGSBURG", port_code: "DELUD"},
  {name: "MACAPA", port_code: "BRMCP"},
  {name: "MACOU", port_code: "CNMCO"},
  {name: "MADRID", port_code: "ESMAD"},
  {name: "MALE", port_code: "MVMLE"},
  {name: "MANAUS", port_code: "BRMAO"},
  {name: "MAYOTTE", port_code: "YTMAM"},
  {name: "MELILLA", port_code: "EAMLI"},
  {name: "MENDOZA", port_code: "ARMZA"},
  {name: "MIRI", port_code: "MYMRI"},
  {name: "MONFALCONE", port_code: "ITMFN"},
  {name: "MONGLA", port_code: "BDMGL"},
  {name: "MONROVIA", port_code: "LRMLW"},
  {name: "MORMUGAO", port_code: "INMRM"},
  {name: "MOSCOW", port_code: "RUMOW"},
  {name: "MUARA", port_code: "BNMUA"},
  {name: "MUKA KUNING", port_code: "IDMUK"},
  {name: "MUKALLA", port_code: "YEMKL"},
  {name: "NANTES", port_code: "FRNCE"},
  {name: "NANTUNG", port_code: "CNNTG"},
  {name: "NORO", port_code: "SBNRO"},
  {name: "NOSE BE", port_code: "MGNSB"},
  {name: "NOSY BE", port_code: "MGNSB"},
  {name: "OKINAWA", port_code: "JPOKI"},
  {name: "ORANJESTAD", port_code: "AWORA"},
  {name: "PASIR GUDANG", port_code: "MYPGU"},
  {name: "PATRAI", port_code: "GRPAT"},
  {name: "PEKAN BARU", port_code: "IDPKB"},
  {name: "PERAWANG", port_code: "IDPRW"},
  {name: "PHILIPSBURG", port_code: "SXPHI"},
  {name: "PLAJU", port_code: "IDPLJ"},
  {name: "POINT LISAS", port_code: "TTPTL"},
  {name: "POINTE DES GALETS", port_code: "REPDG"},
  {name: "POINTE NOIRE", port_code: "CGPNR"},
  {name: "PONAPE", port_code: "FMPNI"},
  {name: "PONCE", port_code: "PRPSE"},
  {name: "PONTIANAK", port_code: "IDPNK"},
  {name: "PORT BLAIR", port_code: "INPBR"},
  {name: "PORT CHALMERS", port_code: "NZPOC"},
  {name: "PORT DE-FRANCE", port_code: "MQFDF"},
  {name: "PORT NOVO", port_code: "BJPNO"},
  {name: "PORT OF SPAIN", port_code: "TTPOS"},
  {name: "PORT PEGASUS", port_code: "NZPPG"},
  {name: "PORT SAIDEL SALVADOR", port_code: "EGPSD"},
  {name: "PORT/NSICT", port_code: "INNSI"},
  {name: "PRETORIA", port_code: "ZAPRQ"},
  {name: "QUINGHUANG", port_code: "CNQHD"},
  {name: "RABAUL", port_code: "PGRBL"},
  {name: "REGGIO", port_code: "ITREG"},
  {name: "RIO GRANDE DO SUL", port_code: "BRRIG"},
  {name: "RIO HAINA", port_code: "DORIH"},
  {name: "RIYADH", port_code: "SARUH"},
  {name: "ROSTOV", port_code: "RUROV"},
  {name: "SALINA CRUZ", port_code: "MXSCZ"},
  {name: "SALONICA", port_code: "GRTHE"},
  {name: "SAMARINDA", port_code: "IDSMR"},
  {name: "SAMPIT", port_code: "IDSMP"},
  {name: "SAN JOSE", port_code: "CRSJO"},
  {name: "SAN LORENZO", port_code: "ARSLR"},
  {name: "SAN PEDRO", port_code: "CIVSPD"},
  {name: "SAN PEDRO SULA", port_code: "HNSAP"},
  {name: "SANTA CRUZ DE TENERIFE", port_code: "ESSCT"},
  {name: "SANTO", port_code: "VUSAN"},
  {name: "SANTO TOMAS DE CASTILLA", port_code: "GTSTC"},
  {name: "SEKONDI", port_code: "GHSEK"},
  {name: "SEKUPANG", port_code: "IDSKP"},
  {name: "SHIKOU", port_code: "CNSHK"},
  {name: "SITTIVE", port_code: "MMSIT"},
  {name: "SOFIA", port_code: "BGSOF"},
  {name: "SONDERBURG", port_code: "DKSON"},
  {name: "ST. GEORGE'S", port_code: "GDGND"},
  {name: "ST. JOHNS", port_code: "AGANU"},
  {name: "ST. LOUIS", port_code: "SNDKR"},
  {name: "STAVANGER", port_code: "NOSVG"},
  {name: "SUAPE", port_code: "BRSUA"},
  {name: "TANJONG MANI", port_code: "MYTNM"},
  {name: "TANJUNG UNCANG", port_code: "IDTJU"},
  {name: "TENERIFE", port_code: "ESSCT"},
  {name: "TOAMASINE", port_code: "MGTOM"},
  {name: "TOLEDO", port_code: "ESTOL"},
  {name: "TOLIARY", port_code: "MGTLY"},
  {name: "TRUK", port_code: "FMTRK"},
  {name: "UJUNG PANDANG", port_code: "IDUPG"},
  {name: "VILA", port_code: "VUVLI"},
  {name: "WEXFORD", port_code: "IEWEX"},
  {name: "WILLEMSTAD", port_code: "CWCUR"},
  {name: "ZAMBOANGA", port_code: "PHZMB"},
  {name: "ZARAGOZA", port_code: "ESZAR"}
];
PortList.insert_all(ports)
